checksumBehavior: update

enableInlineBuilds: true

enableMessageNames: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

npmRegistryServer: https://registry.npmjs.org
